metadata:
  name: Kitepower V3.20
  description: Config for the Kitepower V3.20 soft kite pumping ground gen system
  note: None
  awesIO_version: 0.1.0
  schema: system_schema.yml
assembly:
  airborne_type: soft_kite
  generation_type: pumping_ground_gen
components:
  wing:
    name: Kitepower V3.20
    type: LEI_soft_kite
    version: 1.0
    aerodynamics:
      simple_aero_model: # Parameters for simple models
        lift_coefficient_reel_out: 0.9
        drag_coefficient_reel_out: 0.2
        lift_coefficient_reel_in: 0.17 # 0.20
        drag_coefficient_reel_in: 0.1
    structure:
      projected_surface_area_m2: 19.75
      mass_kg: 12.0
  bridle:
    name: Kitepower V3.20 Bridle
    type: LEI_soft_kite_bridle 
    version: 1.0
    aerodynamics:
    structure:
      mass_kg: 2.8
  control_system:
    name: Kitepower V3.20 KCU
    type: kite_control_unit
    version: 1.0
    structure:
      mass_kg: 8.0
  tether:
    name: Kitepower V3.20
    type: non_conductive_tether
    version: 1.0
    aerodynamics:
      drag_coefficient: 1.1
    structure:
      length_m: 300.0
      diameter_m: 0.004
      density_kg_m3: 724.0
      max_tether_force_n: 5000
      conductive: false
      material:
        type: dyneema
        youngs_modulus_pa: 0.85e9
  ground_station:
    name: example_pumping_ground_gen_station
    type: pumping_ground_gen_station
    version: 1.0
    structure:
    drum:
      type: electric_winch
      max_tether_speed_m_s: 10.0
    generator:
      type: permanent_magnet_synchronous
      max_power_kw: 15.0
      efficiency: 1
    storage:
      type: battery_bank
      capacity_kwh: 100.0
      max_charge_rate_kw: 50.0
      max_discharge_rate_kw: 50.0
      efficiency: 1
      state_of_charge_initial: 0.5
