metadata:
  n_clusters: 1
  n_wind_speed_bins: 50
  reference_height_m: 100.0
  total_samples: 6938
  wind_speed_range_m_s:
  - 4.202350933834351
  - 27.388015720125917
  data_source: ERA5
  location:
    latitude: 52.0
    longitude: 4.0
  time_range:
    start_year: 2011
    end_year: 2011
    years_included:
    - 2011
  altitude_range_m: !!python/tuple
  - 0
  - 500
  clustering_parameters:
    n_pcs: 5
    explained_variance:
    - 0.5352556338896476
    - 0.14783822383480397
    - 0.053129960814736234
    - 0.02028791916990424
    - 0.01300656933059528
    fit_inertia: 5338.148495934405
  time_created: '2025-12-14T16:03:44.480504'
altitudes:
- 0.0
- 10.0
- 20.0
- 30.0
- 40.0
- 50.0
- 60.0
- 70.0
- 80.0
- 90.0
- 100.0
- 110.0
- 120.0
- 130.0
- 140.0
- 150.0
- 160.0
- 170.0
- 180.0
- 190.0
- 200.0
- 210.0
- 220.0
- 230.0
- 240.0
- 250.0
- 260.0
- 270.0
- 280.0
- 290.0
- 300.0
- 310.0
- 320.0
- 330.0
- 340.0
- 350.0
- 360.0
- 370.0
- 380.0
- 390.0
- 400.0
- 410.0
- 420.0
- 430.0
- 440.0
- 450.0
- 460.0
- 470.0
- 480.0
- 490.0
- 500.0
wind_speed_bins:
  bin_edges_m_s:
  - 4.202350933834351
  - 4.666064229560183
  - 5.129777525286014
  - 5.593490821011845
  - 6.057204116737677
  - 6.520917412463508
  - 6.984630708189339
  - 7.448344003915171
  - 7.912057299641003
  - 8.375770595366834
  - 8.839483891092666
  - 9.303197186818497
  - 9.766910482544327
  - 10.230623778270159
  - 10.69433707399599
  - 11.15805036972182
  - 11.621763665447652
  - 12.085476961173484
  - 12.549190256899315
  - 13.012903552625147
  - 13.476616848350979
  - 13.94033014407681
  - 14.404043439802642
  - 14.867756735528472
  - 15.331470031254304
  - 15.795183326980135
  - 16.25889662270597
  - 16.7226099184318
  - 17.186323214157632
  - 17.65003650988346
  - 18.11374980560929
  - 18.577463101335123
  - 19.041176397060955
  - 19.504889692786787
  - 19.968602988512618
  - 20.432316284238446
  - 20.896029579964278
  - 21.35974287569011
  - 21.82345617141594
  - 22.287169467141773
  - 22.750882762867604
  - 23.214596058593436
  - 23.678309354319268
  - 24.1420226500451
  - 24.60573594577093
  - 25.069449241496763
  - 25.533162537222594
  - 25.996875832948426
  - 26.460589128674258
  - 26.92430242440009
  - 27.388015720125917
  bin_centers_m_s:
  - 4.434207581697267
  - 4.897920877423099
  - 5.361634173148929
  - 5.825347468874761
  - 6.289060764600592
  - 6.7527740603264235
  - 7.216487356052255
  - 7.680200651778087
  - 8.143913947503918
  - 8.60762724322975
  - 9.071340538955582
  - 9.535053834681413
  - 9.998767130407243
  - 10.462480426133075
  - 10.926193721858905
  - 11.389907017584736
  - 11.853620313310568
  - 12.3173336090364
  - 12.781046904762231
  - 13.244760200488063
  - 13.708473496213895
  - 14.172186791939726
  - 14.635900087665558
  - 15.099613383391388
  - 15.56332667911722
  - 16.027039974843053
  - 16.490753270568884
  - 16.954466566294716
  - 17.418179862020544
  - 17.881893157746376
  - 18.345606453472207
  - 18.80931974919804
  - 19.27303304492387
  - 19.736746340649702
  - 20.200459636375534
  - 20.664172932101362
  - 21.127886227827194
  - 21.591599523553025
  - 22.055312819278857
  - 22.51902611500469
  - 22.98273941073052
  - 23.446452706456352
  - 23.910166002182184
  - 24.373879297908015
  - 24.837592593633847
  - 25.30130588935968
  - 25.76501918508551
  - 26.228732480811342
  - 26.692445776537173
  - 27.156159072263
clusters:
- id: 1
  u_normalized:
  - 0.7145862273812918
  - 0.7145862273812918
  - 0.7709408579966467
  - 0.827295488612002
  - 0.8612262695389042
  - 0.8927757566935864
  - 0.9190342666950426
  - 0.9418814887950875
  - 0.9642513144785444
  - 0.9821256572392746
  - 1.0
  - 1.0166284466877706
  - 1.030901933746332
  - 1.0451754208048936
  - 1.0583915225481058
  - 1.069536650685543
  - 1.0806817788229814
  - 1.0916849602684633
  - 1.0999911545669445
  - 1.108297348865415
  - 1.1166035431639016
  - 1.1237496027425007
  - 1.1295116419535325
  - 1.135273681164558
  - 1.1410357203755874
  - 1.1456117776501504
  - 1.1491445275069112
  - 1.152677277363683
  - 1.1562100272204394
  - 1.1592703579043624
  - 1.1609058420067335
  - 1.1625413261091058
  - 1.164176810211479
  - 1.1658122943138527
  - 1.1665565971564609
  - 1.1666502451692877
  - 1.166743893182101
  - 1.1668375411949305
  - 1.1669311892077496
  - 1.1664548168490951
  - 1.165375583439123
  - 1.164296350029147
  - 1.1632171166191703
  - 1.1621378832091995
  - 1.1610586497992188
  - 1.1592447788777052
  - 1.1573856754979464
  - 1.155526572118183
  - 1.1536674687384239
  - 1.1518083653586646
  - 1.1499492619789
  v_normalized:
  - 0.026906408605257264
  - 0.026906408605257264
  - 0.02735416678493082
  - 0.02780192496460455
  - 0.025622190479586044
  - 0.0231634302248658
  - 0.01964906428321394
  - 0.01545411046446159
  - 0.01112774066060058
  - 0.005563870330300299
  - 1.8151761486954298e-19
  - -0.00594731671622171
  - -0.012619413595427776
  - -0.019291510474633858
  - -0.026218628205747024
  - -0.0336452246468084
  - -0.041071821087869734
  - -0.04851577488219974
  - -0.05628951838863578
  - -0.06406326189507142
  - -0.07183700540150734
  - -0.07959030037507464
  - -0.08731920060767555
  - -0.09504810084027618
  - -0.10277700107287766
  - -0.11027421616396418
  - -0.11756761801025974
  - -0.12486101985655536
  - -0.1321544217028501
  - -0.13928596402977578
  - -0.1459293276456695
  - -0.152572691261564
  - -0.15921605487745727
  - -0.16585941849335226
  - -0.17205278574495905
  - -0.1779176089382098
  - -0.18378243213146142
  - -0.18964725532471358
  - -0.19551207851796515
  - -0.2009178210842151
  - -0.20583803393384195
  - -0.2107582467834686
  - -0.2156784596330936
  - -0.22059867248272053
  - -0.22551888533234682
  - -0.22956438126354795
  - -0.23355601988979152
  - -0.23754765851603668
  - -0.2415392971422811
  - -0.24553093576852555
  - -0.24952257439477005
probability_matrix:
  description: Probability of each cluster occurring at each wind speed bin (% of
    total samples)
  dimensions: '[n_clusters x n_wind_speed_bins]'
  data:
  - - 1.6431248198328048
    - 4.078985298356875
    - 5.477082732776016
    - 5.087921591236667
    - 5.53473623522629
    - 5.707696742577112
    - 5.63562986451427
    - 4.914961083885846
    - 5.246468722974921
    - 4.799654078985299
    - 4.886134332660709
    - 4.2087056788699915
    - 4.194292303257423
    - 4.223119054482559
    - 3.5312770250792735
    - 3.6898241568175267
    - 3.2718362640530416
    - 2.7241279907754397
    - 2.680887863937734
    - 2.4214471029115017
    - 2.118766215047564
    - 1.8737388296339001
    - 1.6719515710579418
    - 1.4845776880945518
    - 1.1963101758431824
    - 1.181896800230614
    - 0.9224560392043817
    - 0.994522917267224
    - 0.49005477082732773
    - 0.7350821562409917
    - 0.590948400115307
    - 0.3603343903142116
    - 0.38916114153934855
    - 0.28826751225136926
    - 0.33150763908907466
    - 0.23061400980109542
    - 0.23061400980109542
    - 0.17296050735082155
    - 0.3026808878639377
    - 0.17296050735082155
    - 0.08648025367541078
    - 0.057653502450273855
    - 0.028826751225136928
    - 0.057653502450273855
    - 0.014413375612568464
    - 0.0
    - 0.0
    - 0.014413375612568464
    - 0.0
    - 0.04324012683770539
