metadata:
  n_clusters: 1
  n_wind_speed_bins: 50
  n_wind_direction_bins: 10
  wind_direction_bin_width_deg: 36.0
  reference_height_m: 200.0
  total_samples: 61320
  wind_speed_range_m_s:
  - 0.10773529124307026
  - 30.8372462083865
  data_source: ERA5
  location:
    latitude: 54.126495365765976
    longitude: -9.781335066728756
  time_range:
    start_year: 2011
    end_year: 2017
    years_included:
    - 2011
    - 2012
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
  altitude_range_m:
  - 0
  - 500
  clustering_parameters:
    n_pcs: 5
    explained_variance:
    - 0.1542546917827808
    - 0.07705490225101586
    - 0.010738732882120253
    - 0.006983507298608359
    - 0.004050070272466663
    fit_inertia: 13092.1800010159
  time_created: '2026-02-23T15:22:23.197095'
altitudes:
- 0.0
- 10.0
- 20.0
- 30.0
- 40.0
- 50.0
- 60.0
- 70.0
- 80.0
- 90.0
- 100.0
- 110.0
- 120.0
- 130.0
- 140.0
- 150.0
- 160.0
- 170.0
- 180.0
- 190.0
- 200.0
- 210.0
- 220.0
- 230.0
- 240.0
- 250.0
- 260.0
- 270.0
- 280.0
- 290.0
- 300.0
- 310.0
- 320.0
- 330.0
- 340.0
- 350.0
- 360.0
- 370.0
- 380.0
- 390.0
- 400.0
- 410.0
- 420.0
- 430.0
- 440.0
- 450.0
- 460.0
- 470.0
- 480.0
- 490.0
- 500.0
wind_speed_bins:
  bin_edges_m_s:
  - 0.10773529124307026
  - 0.7223255095859388
  - 1.3369157279288073
  - 1.951505946271676
  - 2.5660961646145446
  - 3.180686382957413
  - 3.795276601300282
  - 4.40986681964315
  - 5.024457037986019
  - 5.639047256328888
  - 6.253637474671756
  - 6.868227693014624
  - 7.482817911357493
  - 8.09740812970036
  - 8.71199834804323
  - 9.326588566386098
  - 9.941178784728967
  - 10.555769003071836
  - 11.170359221414705
  - 11.784949439757572
  - 12.39953965810044
  - 13.01412987644331
  - 13.628720094786178
  - 14.243310313129047
  - 14.857900531471916
  - 15.472490749814783
  - 16.08708096815765
  - 16.70167118650052
  - 17.316261404843388
  - 17.930851623186257
  - 18.545441841529126
  - 19.160032059871995
  - 19.774622278214864
  - 20.389212496557732
  - 21.0038027149006
  - 21.61839293324347
  - 22.23298315158634
  - 22.847573369929208
  - 23.462163588272073
  - 24.076753806614942
  - 24.69134402495781
  - 25.30593424330068
  - 25.92052446164355
  - 26.535114679986417
  - 27.149704898329286
  - 27.764295116672155
  - 28.378885335015024
  - 28.993475553357893
  - 29.608065771700762
  - 30.222655990043627
  - 30.8372462083865
  bin_centers_m_s:
  - 0.4150304004145045
  - 1.029620618757373
  - 1.6442108371002417
  - 2.25880105544311
  - 2.8733912737859786
  - 3.4879814921288474
  - 4.102571710471716
  - 4.717161928814584
  - 5.331752147157453
  - 5.946342365500321
  - 6.56093258384319
  - 7.175522802186059
  - 7.790113020528927
  - 8.404703238871795
  - 9.019293457214664
  - 9.633883675557533
  - 10.248473893900401
  - 10.86306411224327
  - 11.477654330586137
  - 12.092244548929006
  - 12.706834767271875
  - 13.321424985614744
  - 13.936015203957613
  - 14.550605422300482
  - 15.16519564064335
  - 15.779785858986216
  - 16.394376077329085
  - 17.008966295671954
  - 17.623556514014822
  - 18.23814673235769
  - 18.85273695070056
  - 19.46732716904343
  - 20.081917387386298
  - 20.696507605729167
  - 21.311097824072036
  - 21.925688042414905
  - 22.540278260757773
  - 23.154868479100642
  - 23.769458697443508
  - 24.384048915786376
  - 24.998639134129245
  - 25.613229352472114
  - 26.227819570814983
  - 26.842409789157852
  - 27.45700000750072
  - 28.07159022584359
  - 28.68618044418646
  - 29.300770662529327
  - 29.915360880872193
  - 30.52995109921506
wind_direction_bins:
  bin_edges_deg:
  - 0.0
  - 36.0
  - 72.0
  - 108.0
  - 144.0
  - 180.0
  - 216.0
  - 252.0
  - 288.0
  - 324.0
  - 360.0
  bin_centers_deg:
  - 18.0
  - 54.0
  - 90.0
  - 126.0
  - 162.0
  - 198.0
  - 234.0
  - 270.0
  - 306.0
  - 342.0
clusters:
- id: 1
  u_normalized:
  - 0.6470650153896736
  - 0.6470650153896736
  - 0.6963715714231145
  - 0.7456781274565544
  - 0.7744390725705868
  - 0.8010181828967328
  - 0.8229810808704913
  - 0.8419677366697156
  - 0.8605737215689856
  - 0.8755950554937574
  - 0.8906163894185454
  - 0.9047548198340266
  - 0.9172244095122636
  - 0.9296939991905255
  - 0.9415185073448274
  - 0.9520795718043129
  - 0.9626406362638101
  - 0.9731216204921173
  - 0.9820810803280765
  - 0.9910405401640463
  - 1.0
  - 1.0082946004612146
  - 1.0157960353525224
  - 1.0232974702438198
  - 1.0307989051351198
  - 1.0375528942573695
  - 1.0436493558985724
  - 1.0497458175397671
  - 1.0558422791809645
  - 1.0616138495790515
  - 1.0664055271114117
  - 1.0711972046438036
  - 1.0759888821761647
  - 1.0807805597085194
  - 1.0848704924390868
  - 1.08844807861884
  - 1.092025664798603
  - 1.095603250978374
  - 1.0991808371581113
  - 1.1022359723180866
  - 1.1047385563995196
  - 1.1072411404809768
  - 1.1097437245624022
  - 1.1122463086438388
  - 1.1147488927252696
  - 1.1163958071136264
  - 1.1179900369561477
  - 1.1195842667986595
  - 1.1211784966411644
  - 1.1227727264836642
  - 1.1243669563261687
  v_normalized:
  - 0.03950051599178717
  - 0.03950051599178717
  - 0.04154354580902777
  - 0.04358657562626848
  - 0.04337684530235025
  - 0.04292788381299778
  - 0.04180180570642118
  - 0.04023916557031802
  - 0.03860334899556111
  - 0.036278454290146624
  - 0.033953559584731834
  - 0.03141147097870866
  - 0.028458848236851568
  - 0.02550622549499492
  - 0.022371027082206493
  - 0.01887823963345028
  - 0.015385452184694216
  - 0.011869479450861456
  - 0.007912986300574394
  - 0.003956493150287199
  - -1.2916847216194955e-19
  - -0.004117413752178142
  - -0.008426802959243723
  - -0.012736192166309264
  - -0.017045581373374873
  - -0.021448138029389257
  - -0.02593265402019302
  - -0.030417170010996714
  - -0.03490168600180088
  - -0.0393827151320052
  - -0.043853227666589084
  - -0.04832374020117154
  - -0.05279425273575504
  - -0.057264765270338205
  - -0.06161735223786498
  - -0.06588384130003323
  - -0.07015033036220168
  - -0.07441681942436894
  - -0.07868330848653658
  - -0.08278233183426924
  - -0.08670424123710582
  - -0.0906261506399446
  - -0.09454806004278021
  - -0.09846996944561805
  - -0.10239187884845502
  - -0.10591274514865812
  - -0.10940891877375376
  - -0.11290509239885105
  - -0.11640126602394565
  - -0.1198974396490419
  - -0.12339361327413673
probability_matrix:
  description: Probability of each cluster occurring at each wind speed and direction
    bin (% of total samples)
  dimensions: '[n_clusters x n_wind_speed_bins x n_wind_direction_bins]'
  data:
  - - - 0.009784735812133072
      - 0.013046314416177431
      - 0.004892367906066536
      - 0.004892367906066536
      - 0.013046314416177431
      - 0.016307893020221786
      - 0.008153946510110893
      - 0.019569471624266144
      - 0.009784735812133072
      - 0.004892367906066536
    - - 0.03913894324853229
      - 0.04403131115459883
      - 0.0538160469667319
      - 0.042400521852576645
      - 0.042400521852576645
      - 0.06360078277886498
      - 0.05707762557077625
      - 0.07175472928897587
      - 0.0766470971950424
      - 0.055446836268754074
    - - 0.14024787997390736
      - 0.14840182648401826
      - 0.11904761904761905
      - 0.091324200913242
      - 0.12067840834964123
      - 0.1532941943900848
      - 0.1288323548597521
      - 0.15003261578604044
      - 0.13209393346379647
      - 0.16307893020221786
    - - 0.17775603392041747
      - 0.17938682322243965
      - 0.14840182648401826
      - 0.18427919112850621
      - 0.17612524461839532
      - 0.18917155903457272
      - 0.2136333985649054
      - 0.26581865622961515
      - 0.1924331376386171
      - 0.18917155903457272
    - - 0.27723418134377037
      - 0.24951076320939336
      - 0.2576647097195042
      - 0.19732550554468362
      - 0.2364644487932159
      - 0.26581865622961515
      - 0.2837573385518591
      - 0.2087410306588389
      - 0.2968036529680365
      - 0.24951076320939336
    - - 0.3587736464448793
      - 0.29191128506197
      - 0.27723418134377037
      - 0.2609262883235486
      - 0.2380952380952381
      - 0.25929549902152643
      - 0.30984996738421394
      - 0.24951076320939336
      - 0.3245270711024136
      - 0.3065883887801696
    - - 0.3457273320287019
      - 0.3180039138943248
      - 0.31148075668623615
      - 0.2609262883235486
      - 0.2364644487932159
      - 0.29354207436399216
      - 0.30984996738421394
      - 0.3180039138943248
      - 0.32778864970645794
      - 0.35551206784083494
    - - 0.5234833659491194
      - 0.4582517938682322
      - 0.35225048923679064
      - 0.3016960208741031
      - 0.2902804957599478
      - 0.29354207436399216
      - 0.39465101108936723
      - 0.3065883887801696
      - 0.3897586431833007
      - 0.48434442270058714
    - - 0.5593607305936072
      - 0.5251141552511416
      - 0.48434442270058714
      - 0.36203522504892366
      - 0.3082191780821918
      - 0.32289628180039137
      - 0.4207436399217221
      - 0.32778864970645794
      - 0.3457273320287019
      - 0.5642530984996739
    - - 0.684931506849315
      - 0.5609915198956295
      - 0.428897586431833
      - 0.3440965427266797
      - 0.27723418134377037
      - 0.2690802348336595
      - 0.3424657534246575
      - 0.37181996086105673
      - 0.4973907371167645
      - 0.7093933463796477
    - - 0.7974559686888453
      - 0.5952380952380952
      - 0.4044357469015003
      - 0.3310502283105023
      - 0.2804957599478147
      - 0.22667971298108283
      - 0.37345075016307894
      - 0.428897586431833
      - 0.5528375733855186
      - 0.6898238747553815
    - - 0.8137638617090671
      - 0.6963470319634704
      - 0.410958904109589
      - 0.31963470319634707
      - 0.3065883887801696
      - 0.23483365949119372
      - 0.3506196999347684
      - 0.3587736464448793
      - 0.5185909980430529
      - 0.7273320287018917
    - - 0.7893020221787345
      - 0.6506849315068494
      - 0.4174820613176778
      - 0.3669275929549902
      - 0.2217873450750163
      - 0.23320287018917157
      - 0.2902804957599478
      - 0.3440965427266797
      - 0.556099151989563
      - 0.6343770384866275
    - - 0.8643183300717547
      - 0.6196999347684279
      - 0.46803652968036524
      - 0.39791258969341164
      - 0.2168949771689498
      - 0.15003261578604044
      - 0.273972602739726
      - 0.3457273320287019
      - 0.5332681017612525
      - 0.7224396607958251
    - - 0.8675799086757991
      - 0.720808871493803
      - 0.4615133724722766
      - 0.37345075016307894
      - 0.2054794520547945
      - 0.11741682974559686
      - 0.15166340508806264
      - 0.29191128506197
      - 0.46640574037834315
      - 0.7191780821917808
    - - 0.8056099151989562
      - 0.6800391389432485
      - 0.4207436399217221
      - 0.3604044357469015
      - 0.20221787345075015
      - 0.10110893672537508
      - 0.19569471624266144
      - 0.26418786692759294
      - 0.43215916503587737
      - 0.7322243966079582
    - - 0.7420091324200913
      - 0.7077625570776256
      - 0.40932811480756687
      - 0.35551206784083494
      - 0.2609262883235486
      - 0.13861709067188518
      - 0.13209393346379647
      - 0.246249184605349
      - 0.4191128506196999
      - 0.6881930854533594
    - - 0.7681017612524462
      - 0.6686236138290933
      - 0.401174168297456
      - 0.3473581213307241
      - 0.2136333985649054
      - 0.17123287671232876
      - 0.14024787997390736
      - 0.2902804957599478
      - 0.3913894324853229
      - 0.7534246575342466
    - - 0.821917808219178
      - 0.6686236138290933
      - 0.46966731898238745
      - 0.35225048923679064
      - 0.24951076320939336
      - 0.05870841487279843
      - 0.14187866927592954
      - 0.25929549902152643
      - 0.3310502283105023
      - 0.5577299412915852
    - - 0.8039791258969342
      - 0.684931506849315
      - 0.42400521852576645
      - 0.3897586431833007
      - 0.21037181996086105
      - 0.0766470971950424
      - 0.16470971950424004
      - 0.246249184605349
      - 0.3147423352902805
      - 0.5316373124592303
    - - 0.8561643835616438
      - 0.7354859752120027
      - 0.48108284409654267
      - 0.33594259621656886
      - 0.18427919112850621
      - 0.08969341161121983
      - 0.10273972602739725
      - 0.22504892367906068
      - 0.3131115459882583
      - 0.5430528375733855
    - - 0.802348336594912
      - 0.6278538812785388
      - 0.37997390737116765
      - 0.35225048923679064
      - 0.16797129810828443
      - 0.06523157208088715
      - 0.08153946510110893
      - 0.19732550554468362
      - 0.2397260273972603
      - 0.5039138943248532
    - - 0.6898238747553815
      - 0.647423352902805
      - 0.38649706457925637
      - 0.2968036529680365
      - 0.182648401826484
      - 0.05055446836268754
      - 0.05707762557077625
      - 0.11089367253750815
      - 0.18917155903457272
      - 0.48271363339856493
    - - 0.7371167645140249
      - 0.6278538812785388
      - 0.38649706457925637
      - 0.23483365949119372
      - 0.18427919112850621
      - 0.03913894324853229
      - 0.04403131115459883
      - 0.10273972602739725
      - 0.17449445531637311
      - 0.43215916503587737
    - - 0.5870841487279843
      - 0.6409001956947162
      - 0.31637312459230266
      - 0.228310502283105
      - 0.16144814090019569
      - 0.029354207436399216
      - 0.01793868232224397
      - 0.09947814742335291
      - 0.15492498369210697
      - 0.3457273320287019
    - - 0.5365296803652968
      - 0.5789302022178734
      - 0.3473581213307241
      - 0.182648401826484
      - 0.12557077625570776
      - 0.0228310502283105
      - 0.02446183953033268
      - 0.08153946510110893
      - 0.13372472276581865
      - 0.32778864970645794
    - - 0.49412915851272016
      - 0.49412915851272016
      - 0.2788649706457926
      - 0.20384866275277233
      - 0.08480104370515329
      - 0.03424657534246575
      - 0.014677103718199608
      - 0.052185257664709724
      - 0.1141552511415525
      - 0.24298760600130462
    - - 0.36366601435094587
      - 0.446836268754077
      - 0.2544031311154599
      - 0.19406392694063926
      - 0.091324200913242
      - 0.027723418134377037
      - 0.01141552511415525
      - 0.03424657534246575
      - 0.10437051532941945
      - 0.20384866275277233
    - - 0.35225048923679064
      - 0.4598825831702544
      - 0.27234181343770386
      - 0.17123287671232876
      - 0.055446836268754074
      - 0.009784735812133072
      - 0.01141552511415525
      - 0.016307893020221786
      - 0.0538160469667319
      - 0.2234181343770385
    - - 0.2902804957599478
      - 0.3995433789954338
      - 0.2902804957599478
      - 0.16634050880626222
      - 0.03913894324853229
      - 0.009784735812133072
      - 0.01141552511415525
      - 0.02446183953033268
      - 0.07175472928897587
      - 0.17286366601435094
    - - 0.28212654924983693
      - 0.29517286366601436
      - 0.246249184605349
      - 0.13535551206784086
      - 0.02446183953033268
      - 0.016307893020221786
      - 0.009784735812133072
      - 0.019569471624266144
      - 0.061969993476842795
      - 0.16797129810828443
    - - 0.24951076320939336
      - 0.2560339204174821
      - 0.25277234181343766
      - 0.08969341161121983
      - 0.03424657534246575
      - 0.004892367906066536
      - 0.01141552511415525
      - 0.008153946510110893
      - 0.03261578604044357
      - 0.12067840834964123
    - - 0.15655577299412915
      - 0.2544031311154599
      - 0.18427919112850621
      - 0.09621656881930855
      - 0.0228310502283105
      - 0.0065231572080887154
      - 0.0
      - 0.01793868232224397
      - 0.029354207436399216
      - 0.1141552511415525
    - - 0.11741682974559686
      - 0.19732550554468362
      - 0.17123287671232876
      - 0.0538160469667319
      - 0.0065231572080887154
      - 0.0
      - 0.0
      - 0.013046314416177431
      - 0.016307893020221786
      - 0.10110893672537508
    - - 0.12557077625570776
      - 0.18754076973255054
      - 0.1141552511415525
      - 0.04403131115459883
      - 0.014677103718199608
      - 0.004892367906066536
      - 0.0
      - 0.0065231572080887154
      - 0.01141552511415525
      - 0.055446836268754074
    - - 0.12557077625570776
      - 0.18101761252446183
      - 0.11089367253750815
      - 0.03424657534246575
      - 0.013046314416177431
      - 0.0
      - 0.0
      - 0.0016307893020221789
      - 0.009784735812133072
      - 0.05870841487279843
    - - 0.07990867579908677
      - 0.15166340508806264
      - 0.08643183300717547
      - 0.03750815394651011
      - 0.013046314416177431
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.009784735812133072
      - 0.045662100456621
    - - 0.055446836268754074
      - 0.1076320939334638
      - 0.08153946510110893
      - 0.030984996738421398
      - 0.0065231572080887154
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.030984996738421398
    - - 0.05055446836268754
      - 0.1141552511415525
      - 0.06033920417482062
      - 0.016307893020221786
      - 0.0016307893020221789
      - 0.0032615786040443577
      - 0.0
      - 0.0
      - 0.0016307893020221789
      - 0.0228310502283105
    - - 0.03913894324853229
      - 0.08153946510110893
      - 0.052185257664709724
      - 0.01141552511415525
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.013046314416177431
    - - 0.03750815394651011
      - 0.06686236138290932
      - 0.04403131115459883
      - 0.029354207436399216
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0016307893020221789
      - 0.0065231572080887154
    - - 0.03261578604044357
      - 0.05707762557077625
      - 0.016307893020221786
      - 0.008153946510110893
      - 0.004892367906066536
      - 0.0
      - 0.0
      - 0.0
      - 0.0016307893020221789
      - 0.0065231572080887154
    - - 0.02446183953033268
      - 0.04729288975864318
      - 0.026092628832354862
      - 0.004892367906066536
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0032615786040443577
    - - 0.014677103718199608
      - 0.02446183953033268
      - 0.013046314416177431
      - 0.0065231572080887154
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0016307893020221789
    - - 0.021200260926288322
      - 0.027723418134377037
      - 0.016307893020221786
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0016307893020221789
    - - 0.019569471624266144
      - 0.029354207436399216
      - 0.01141552511415525
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.019569471624266144
      - 0.021200260926288322
      - 0.0016307893020221789
      - 0.004892367906066536
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0016307893020221789
      - 0.0
    - - 0.0032615786040443577
      - 0.016307893020221786
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0032615786040443577
      - 0.004892367906066536
      - 0.0
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0065231572080887154
      - 0.0016307893020221789
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
