metadata:
  description: Ground station configuration including electrical efficiencies and power conversion
  note: Configuration for AWE system ground station component

generator:
  nominal_power_w: 150000.0
  efficiency: 0.95

winch:
  nominal_tether_force_n: 42000.0
  reel_out_speed_limit_m_s: 10.0
  reel_in_speed_limit_m_s: 18.0

storage:
  efficiency: 0.95



